import { useState, type FormEvent } from 'react';
import { Vote } from 'lucide-react';
import type { Proposal } from '@/types';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';

export function NewProposalModal({ open, onOpenChange, onSubmit, stokvelId, totalVoters }: { open: boolean; onOpenChange: (open: boolean) => void; onSubmit: (proposal: Proposal) => void; stokvelId: string; totalVoters: number }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState<Proposal['category']>('Rules & Penalties'); const [deadline, setDeadline] = useState(''); const [error, setError] = useState('');
  const submit = (event: FormEvent) => { event.preventDefault(); if (title.trim().length < 5 || description.trim().length < 10 || !deadline) { setError('Add a clear title, description and closing date.'); return; } onSubmit({ id: crypto.randomUUID(), stokvelId, title: title.trim(), description: description.trim(), category, deadline, createdBy: 'You', votesFor: 0, votesAgainst: 0, totalVoters, status: 'active', userVoted: null }); setTitle(''); setDescription(''); setDeadline(''); setError(''); onOpenChange(false); };
  const field = 'h-11 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground outline-none focus:border-primary';
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] overflow-y-auto rounded-xl border-border bg-surface-card"><DialogHeader><DialogTitle className="flex items-center gap-2"><Vote className="text-accent" />Create motion</DialogTitle><DialogDescription>Put a clear group decision to a member vote.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><label className="block text-sm">Title<input className={field} value={title} onChange={(e) => setTitle(e.target.value)} /></label><label className="block text-sm">Category<select className={field} value={category} onChange={(e) => setCategory(e.target.value as Proposal['category'])}><option>Rules &amp; Penalties</option><option>Payout Adjustment</option><option>Member Admission</option></select></label><label className="block text-sm">Description<textarea className={`${field} min-h-24 py-3`} value={description} onChange={(e) => setDescription(e.target.value)} /></label><label className="block text-sm">Voting closes<input className={field} type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label>{error && <p className="text-sm text-error">{error}</p>}<DialogFooter><Button type="submit" className="h-11">Publish motion</Button></DialogFooter></form></DialogContent></Dialog>;
}