import { useState } from 'react';
import { Bell, Building2, Check, ChevronDown, LogOut, ShieldCheck, Wallet, X } from 'lucide-react';
import type { AppNotification, Stokvel } from '../types';
import { Button } from '@/components/ui/button';

interface NavbarProps { stokvels: Stokvel[]; activeStokvel: Stokvel; onSelectStokvel: (stokvel: Stokvel) => void; onOpenCreateModal: () => void; onOpenContributionModal: () => void; notifications: AppNotification[]; unreadCount: number; onMarkNotificationsRead: () => void; onSignOut: () => void; saving: boolean; }

export function Navbar({ stokvels, activeStokvel, onSelectStokvel, onOpenCreateModal, onOpenContributionModal, notifications, unreadCount, onMarkNotificationsRead, onSignOut, saving }: NavbarProps) {
  const [groupsOpen, setGroupsOpen] = useState(false); const [noticesOpen, setNoticesOpen] = useState(false);
  return <header className="sticky top-0 z-40 w-full border-b border-border bg-surface-card/95 backdrop-blur-xl">
    <div className="mx-auto flex h-16 max-w-7xl items-center justify-between gap-2 px-3 sm:h-20 sm:px-6 lg:px-8">
      <div className="flex min-w-0 items-center gap-2 sm:gap-5"><div className="flex shrink-0 items-center gap-2"><div className="grid size-10 place-items-center rounded-xl border border-primary/30 bg-primary/10 text-primary"><ShieldCheck className="size-5" /></div><div className="hidden sm:block"><p className="font-extrabold uppercase text-foreground">Sisonke</p><p className="text-[10px] uppercase text-textSecondary">Stokvel platform</p></div></div>
        <div className="relative min-w-0"><button aria-label="Switch group" onClick={() => setGroupsOpen((v) => !v)} className="flex h-11 max-w-[190px] items-center gap-2 rounded-lg border border-border bg-surface px-3 text-left sm:max-w-xs"><Building2 className="size-4 shrink-0 text-primary" /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-foreground">{activeStokvel.name}</span><span className="hidden text-[10px] text-textSecondary sm:block">Active group</span></span><ChevronDown className="size-4 shrink-0 text-textSecondary" /></button>
          {groupsOpen && <div className="absolute left-0 top-12 w-[min(21rem,calc(100vw-1.5rem))] overflow-hidden rounded-xl border border-border bg-surface-card shadow-2xl"><div className="flex items-center justify-between border-b border-border p-3"><span className="text-xs font-bold uppercase text-textSecondary">Your groups</span><button className="text-xs font-semibold text-primary" onClick={() => { setGroupsOpen(false); onOpenCreateModal(); }}>Group settings</button></div>{stokvels.map((s) => <button key={s.id} className="flex w-full items-center justify-between gap-3 border-b border-border/60 px-4 py-3 text-left last:border-0" onClick={() => { onSelectStokvel(s); setGroupsOpen(false); }}><span className="min-w-0"><span className="block truncate text-sm font-semibold">{s.name}</span><span className="text-xs text-textSecondary">R {s.totalBalance.toLocaleString()}</span></span>{s.id === activeStokvel.id && <Check className="size-4 text-primary" />}</button>)}</div>}
        </div></div>
      <div className="flex items-center gap-2"><span className="hidden text-[11px] text-textSecondary lg:block">{saving ? 'Saving…' : 'Saved'}</span><Button className="hidden h-11 sm:flex" onClick={onOpenContributionModal}><Wallet />Record contribution</Button>
        <div className="relative"><Button variant="outline" size="icon" className="size-11" aria-label={`Notifications, ${unreadCount} unread`} onClick={() => setNoticesOpen((v) => !v)}><Bell />{unreadCount > 0 && <span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-accent" />}</Button>{noticesOpen && <div className="fixed inset-x-3 top-[4.5rem] rounded-xl border border-border bg-surface-card p-3 shadow-2xl sm:absolute sm:inset-x-auto sm:right-0 sm:top-12 sm:w-96"><div className="mb-2 flex items-center justify-between"><p className="font-bold">Notifications</p><button aria-label="Close notifications" className="grid size-9 place-items-center" onClick={() => setNoticesOpen(false)}><X className="size-4" /></button></div><div className="max-h-80 space-y-2 overflow-y-auto">{notifications.map((n) => <div key={n.id} className={`rounded-lg border p-3 ${n.read ? 'border-border bg-surface' : 'border-primary/30 bg-primary/5'}`}><p className="text-sm font-semibold">{n.title}</p><p className="mt-1 text-xs leading-relaxed text-textSecondary">{n.message}</p></div>)}</div>{unreadCount > 0 && <Button variant="ghost" className="mt-2 w-full" onClick={onMarkNotificationsRead}>Mark all as read</Button>}</div>}</div>
        <Button variant="ghost" size="icon" className="hidden size-11 sm:inline-flex" aria-label="Sign out" onClick={onSignOut}><LogOut /></Button></div>
    </div>
  </header>;
}