import { Stokvel, Member, Contribution, PayoutSchedule, Loan, Proposal, Transaction } from './types';

export const INITIAL_STOKVELS: Stokvel[] = [
  {
    id: 'stokvel-1',
    name: 'Sisonke Family Savings Club',
    code: 'SWPS-2025',
    type: 'Savings',
    totalBalance: 485000,
    monthlyContribution: 3500,
    targetAmount: 750000,
    cycleDay: 25,
    memberCount: 12,
    currency: 'ZAR',
    bankName: 'First National Bank (FNB)',
    accountNumber: '62849102847',
    photoUrl: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'A community savings club where members contribute monthly and take turns receiving the pooled payout.',
    yieldRate: 11.2,
    createdDate: '2023-01-15',
  },
  {
    id: 'stokvel-2',
    name: 'Imbali Grocery & Annual Savings Club',
    code: 'IGSC-992',
    type: 'Grocery',
    totalBalance: 168400,
    monthlyContribution: 1500,
    targetAmount: 250000,
    cycleDay: 1,
    memberCount: 15,
    currency: 'ZAR',
    bankName: 'Standard Bank',
    accountNumber: '00293847291',
    photoUrl: 'https://images.pexels.com/photos/3810792/pexels-photo-3810792.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Empowering families with annual bulk grocery purchasing power and December liquid cash distributions.',
    yieldRate: 7.8,
    createdDate: '2022-06-10',
  },
  {
    id: 'stokvel-3',
    name: 'Thaba Entrepreneurs Micro-Lending Pool',
    code: 'TEML-404',
    type: 'Loan',
    totalBalance: 295000,
    monthlyContribution: 2500,
    targetAmount: 500000,
    cycleDay: 15,
    memberCount: 10,
    currency: 'ZAR',
    bankName: 'Capitec Bank',
    accountNumber: '1048293021',
    photoUrl: 'https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=800',
    description: 'Providing member micro-business financing with high returns returned directly to group treasury equity.',
    yieldRate: 14.5,
    createdDate: '2023-08-01',
  }
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mem-1',
    stokvelId: 'stokvel-1',
    name: 'Thabo Mokoena',
    role: 'Chairperson',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+27 82 491 0293',
    email: 'thabo.m@sisonke.co.za',
    totalContributed: 45500,
    status: 'paid',
    joinDate: '2023-01-15',
    equityPercentage: 12.5,
    payoutMonth: 'December',
    payoutOrder: 12,
  },
  {
    id: 'mem-2',
    stokvelId: 'stokvel-1',
    name: 'Nomvula Khumalo',
    role: 'Treasurer',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+27 73 182 9384',
    email: 'nomvula.k@gmail.com',
    totalContributed: 42000,
    status: 'paid',
    joinDate: '2023-01-15',
    equityPercentage: 11.8,
    payoutMonth: 'May',
    payoutOrder: 5,
  },
  {
    id: 'mem-3',
    stokvelId: 'stokvel-1',
    name: 'Sipho Dlamini',
    role: 'Secretary',
    avatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+27 84 920 1823',
    email: 'sipho.dlamini@outlook.com',
    totalContributed: 38500,
    status: 'pending',
    joinDate: '2023-02-01',
    equityPercentage: 10.2,
    payoutMonth: 'June',
    payoutOrder: 6,
  },
  {
    id: 'mem-4',
    stokvelId: 'stokvel-1',
    name: 'Zanele Naidoo',
    role: 'Member',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+27 71 883 9201',
    email: 'zanele.n@techfirm.co.za',
    totalContributed: 35000,
    status: 'overdue',
    joinDate: '2023-03-10',
    equityPercentage: 9.5,
    payoutMonth: 'July',
    payoutOrder: 7,
  },
  {
    id: 'mem-5',
    stokvelId: 'stokvel-1',
    name: 'Kagiso Lekota',
    role: 'Member',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+27 83 291 0022',
    email: 'k.lekota@construction.co.za',
    totalContributed: 42000,
    status: 'paid',
    joinDate: '2023-01-15',
    equityPercentage: 11.8,
    payoutMonth: 'August',
    payoutOrder: 8,
  },
  {
    id: 'mem-6',
    stokvelId: 'stokvel-1',
    name: 'Lerato Ndlovu',
    role: 'Member',
    avatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
    phone: '+27 79 384 1029',
    email: 'lerato.ndlovu@health.gov.za',
    totalContributed: 31500,
    status: 'paid',
    joinDate: '2023-04-01',
    equityPercentage: 8.5,
    payoutMonth: 'September',
    payoutOrder: 9,
  }
];

export const INITIAL_CONTRIBUTIONS: Contribution[] = [
  {
    id: 'cnt-1',
    stokvelId: 'stokvel-1',
    memberId: 'mem-1',
    memberName: 'Thabo Mokoena',
    memberAvatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=200',
    amount: 3500,
    date: '2025-05-24',
    cycleMonth: 'May 2025',
    status: 'verified',
    paymentMethod: 'EFT',
    reference: 'STK-THABO-05',
  },
  {
    id: 'cnt-2',
    stokvelId: 'stokvel-1',
    memberId: 'mem-2',
    memberName: 'Nomvula Khumalo',
    memberAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    amount: 3500,
    date: '2025-05-25',
    cycleMonth: 'May 2025',
    status: 'verified',
    paymentMethod: 'Capitec Pay',
    reference: 'STK-NOMVULA-05',
  },
  {
    id: 'cnt-3',
    stokvelId: 'stokvel-1',
    memberId: 'mem-5',
    memberName: 'Kagiso Lekota',
    memberAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
    amount: 3500,
    date: '2025-05-25',
    cycleMonth: 'May 2025',
    status: 'verified',
    paymentMethod: 'Debit Order',
    reference: 'STK-KAGISO-05',
  },
  {
    id: 'cnt-4',
    stokvelId: 'stokvel-1',
    memberId: 'mem-6',
    memberName: 'Lerato Ndlovu',
    memberAvatar: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=200',
    amount: 3500,
    date: '2025-05-26',
    cycleMonth: 'May 2025',
    status: 'pending',
    paymentMethod: 'EFT',
    reference: 'STK-LERATO-05',
  }
];

export const INITIAL_PAYOUTS: PayoutSchedule[] = [
  {
    id: 'pay-1',
    stokvelId: 'stokvel-1',
    memberId: 'mem-2',
    memberName: 'Nomvula Khumalo',
    memberAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200',
    month: 'May 2025',
    amount: 42000,
    payoutDate: '2025-05-30',
    status: 'upcoming',
    notes: 'Mid-year rotation distribution.',
  },
  {
    id: 'pay-2',
    stokvelId: 'stokvel-1',
    memberId: 'mem-3',
    memberName: 'Sipho Dlamini',
    memberAvatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    month: 'June 2025',
    amount: 42000,
    payoutDate: '2025-06-30',
    status: 'upcoming',
    notes: 'Scheduled regular rotation payout.',
  },
  {
    id: 'pay-3',
    stokvelId: 'stokvel-1',
    memberId: 'mem-4',
    memberName: 'Zanele Naidoo',
    memberAvatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200',
    month: 'April 2025',
    amount: 42000,
    payoutDate: '2025-04-30',
    status: 'completed',
    notes: 'Disbursed via direct FNB EFT transfer. Verified by Chairperson.',
  }
];

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'loan-1',
    stokvelId: 'stokvel-1',
    borrowerId: 'mem-5',
    borrowerName: 'Kagiso Lekota',
    borrowerAvatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=200',
    amount: 25000,
    interestRate: 4.5,
    durationMonths: 6,
    monthlyRepayment: 4812,
    status: 'active',
    startDate: '2025-02-01',
    dueDate: '2025-08-01',
    remainingBalance: 14436,
    purpose: 'Equipment purchase for expanding transport contractor fleet.',
  },
  {
    id: 'loan-2',
    stokvelId: 'stokvel-1',
    borrowerId: 'mem-3',
    borrowerName: 'Sipho Dlamini',
    borrowerAvatar: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200',
    amount: 15000,
    interestRate: 5.0,
    durationMonths: 4,
    monthlyRepayment: 4125,
    status: 'requested',
    startDate: '2025-06-01',
    dueDate: '2025-10-01',
    remainingBalance: 16500,
    purpose: 'Short-term working capital for boutique retail store inventory.',
  }
];

export const INITIAL_PROPOSALS: Proposal[] = [
  {
    id: 'prop-1',
    stokvelId: 'stokvel-1',
    title: 'Introduce R100 late-payment penalty after the 28th',
    description: 'Move R95,000 idle cash balance from primary checking to high-interest fixed deposit account with Standard Bank to maximize compounding.',
    createdBy: 'Nomvula Khumalo (Treasurer)',
    votesFor: 8,
    votesAgainst: 1,
    totalVoters: 12,
    status: 'active',
    deadline: '2025-06-05',
    category: 'Rules & Penalties',
    userVoted: 'for',
  },
  {
    id: 'prop-2',
    stokvelId: 'stokvel-1',
    title: 'Implement R200 Grace Penalty for Late Monthly Deposits (>3 days late)',
    description: 'Introduce a formal late fee to encourage timely contributions before the 25th of every month. Penalties earned fund annual dinner.',
    createdBy: 'Thabo Mokoena (Chairperson)',
    votesFor: 10,
    votesAgainst: 2,
    totalVoters: 12,
    status: 'passed',
    deadline: '2025-04-15',
    category: 'Rules & Penalties',
    userVoted: 'for',
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    stokvelId: 'stokvel-1',
    type: 'deposit',
    amount: 3500,
    description: 'Monthly Stokvel Contribution - Thabo Mokoena',
    date: '2025-05-24',
    memberName: 'Thabo Mokoena',
    reference: 'STK-THABO-05',
    category: 'Contribution',
  },
  {
    id: 'tx-2',
    stokvelId: 'stokvel-1',
    type: 'deposit',
    amount: 3500,
    description: 'Monthly Stokvel Contribution - Nomvula Khumalo',
    date: '2025-05-25',
    memberName: 'Nomvula Khumalo',
    reference: 'STK-NOMVULA-05',
    category: 'Contribution',
  },
  {
    id: 'tx-3',
    stokvelId: 'stokvel-1',
    type: 'loan_repayment',
    amount: 4812,
    description: 'Loan Repayment Installment #3 - Kagiso Lekota',
    date: '2025-05-20',
    memberName: 'Kagiso Lekota',
    reference: 'LN-REP-KAGISO-03',
    category: 'Loan Return',
  },
  {
    id: 'tx-4',
    stokvelId: 'stokvel-1',
    type: 'yield',
    amount: 4120,
    description: 'Quarterly Money Market Interest Yield Distribution',
    date: '2025-05-15',
    reference: 'YIELD-MM-Q1',
    category: 'Interest Earned',
  },
  {
    id: 'tx-5',
    stokvelId: 'stokvel-1',
    type: 'payout',
    amount: 42000,
    description: 'April Rotation Payout - Zanele Naidoo',
    date: '2025-04-30',
    memberName: 'Zanele Naidoo',
    reference: 'PAYOUT-ZANELE-04',
    category: 'Rotation Distribution',
  }
];
